export default {
	images: {
		data: [
			{ dir: "/assets/images/gallery/000.jpeg" },
			{ dir: "/assets/images/gallery/001.jpeg" },
			{ dir: "/assets/images/gallery/002.jpeg" },
			{ dir: "/assets/images/gallery/003.jpeg" },
			{ dir: "/assets/images/gallery/003b.jpeg" },
			{ dir: "/assets/images/gallery/004.jpeg" },
			{ dir: "/assets/images/gallery/005.jpeg" },
			{ dir: "/assets/images/gallery/006.jpeg" },
			{ dir: "/assets/images/gallery/007.jpeg" },
			{ dir: "/assets/images/gallery/008.jpeg" },
			{ dir: "/assets/images/gallery/009.jpeg" },
			{ dir: "/assets/images/gallery/010.jpeg" },
			{ dir: "/assets/images/gallery/011.jpeg" },
			{ dir: "/assets/images/gallery/012.jpg" },
			{ dir: "/assets/images/gallery/013.jpg" },
			{ dir: "/assets/images/gallery/014.jpg" },
			{ dir: "/assets/images/gallery/015.jpeg" },
			{ dir: "/assets/images/gallery/016.jpeg" },
			{ dir: "/assets/images/gallery/017.jpg" },
			{ dir: "/assets/images/gallery/018.jpg" },
			{ dir: "/assets/images/gallery/019.jpg" },
			{ dir: "/assets/images/gallery/020.jpg" },
			{ dir: "/assets/images/gallery/021.jpg" },
			{ dir: "/assets/images/gallery/022.jpeg" },
			{ dir: "/assets/images/gallery/023.jpeg" },
			{ dir: "/assets/images/gallery/024.jpeg" },
		],
	},
	ext: "jpg",
	abs_dir: "/assets/images/gallery/",
	rel_dir: "../assets/images/gallery/",
};
